services:
  valhalla:
    image: ghcr.io/valhalla/valhalla-scripted:latest
    container_name: resq-valhalla
    ports:
      - "127.0.0.1:8002:8002"
    volumes:
      - ./data/valhalla/custom_files:/custom_files
    environment:
      - build_transit=False
      - server_threads=4
      - build_elevation=False
      - build_admins=True
      - build_time_zones=True
      - serve_tiles=True
      - build_tar=True
      - use_tiles_ignore_pbf=True
      - use_default_speeds_config=True
      - force_rebuild=False
    restart: unless-stopped
