// Register all 9 RESQ Static Factors in datasets.registry for provenance and hackathon auditing
import pool from "../config/db.js";
import { initRegistrySchema, upsertDatasetMetadata, getAllDatasets } from "../services/datasets/datasetRegistryService.js";

export const STATIC_FACTOR_REGISTRY = [
  {
    dataset_name: "CartoDEM_Copernicus_GLO30",
    factor: "elevation",
    source_name: "ISRO CartoDEM / Copernicus GLO-30 DEM",
    provider: "NRSC Bhuvan / ESA Copernicus",
    official_url: "https://bhuvan-app1.nrsc.gov.in/2dresources/bhuvanstore.php",
    implementation_url: "https://registry.opendata.aws/copernicus-dem/",
    source_type: "RASTER_GEOTIFF",
    format: "Cloud-Optimized GeoTIFF (COG), 32-bit float elevation (metres above MSL)",
    resolution: "30m (1 arc-second)",
    temporal_coverage: "Static baseline topographic model",
    geographic_coverage: "100% Assam and Meghalaya",
    version: "2024.1",
    processing_status: "REGISTERED",
    notes: "Primary elevation baseline for deriving elevation_mean, elevation_min, elevation_max, and slope.",
  },
  {
    dataset_name: "Topographic_Slope_30m",
    factor: "slope",
    source_name: "Derived from 30m Digital Elevation Model (GDAL/PostGIS Slope)",
    provider: "RESQ Geospatial Pipeline",
    official_url: "https://bhuvan-app1.nrsc.gov.in/2dresources/bhuvanstore.php",
    implementation_url: "Derived via ST_Slope / Horn's Algorithm",
    source_type: "DERIVED_RASTER",
    format: "32-bit float degrees (0° to 90°)",
    resolution: "30m",
    temporal_coverage: "Static baseline",
    geographic_coverage: "100% Assam and Meghalaya",
    version: "1.0",
    processing_status: "REGISTERED",
    notes: "Essential for terrain slope_mean and landslide susceptibility risk modeling in Meghalaya & Assam hills.",
  },
  {
    dataset_name: "NDEM_NRSC_MultiYear_Flood_Inundation",
    factor: "flood_susceptibility",
    source_name: "NDEM / NRSC (National Database for Emergency Management)",
    provider: "ramSeraph/india_natural_disasters",
    official_url: "https://ndem.nrsc.gov.in/",
    implementation_url: "https://github.com/ramSeraph/india_natural_disasters/releases/tag/floods",
    source_type: "VECTOR_GEOJSONL",
    format: "GeoJSONL (MultiPolygon in EPSG:4326)",
    resolution: "30m-50m satellite microwave flood inundation (RISAT/Sentinel-1)",
    temporal_coverage: "1998 to 2013, 2021 (Assam), 2016-2022 (Meghalaya)",
    geographic_coverage: "Assam & Meghalaya flood plains and river basins",
    version: "2022.1",
    processing_status: "PROCESSED",
    notes: "Multi-year historical flood inundation recurrence mapped to normalized 0-100 susceptibility score.",
  },
  {
    dataset_name: "GSI_National_Landslide_Susceptibility_Mapping",
    factor: "landslide_susceptibility",
    source_name: "Geological Survey of India (GSI) / Bhusanket",
    provider: "GSI Bhusanket Geoportal",
    official_url: "https://bhusanket.gsi.gov.in/",
    implementation_url: "https://bhusanket.gsi.gov.in/geoserver/wms",
    source_type: "VECTOR_OGC_WMS_SHP",
    format: "Vector Shapefile / WMS (5-tier zonation: Very High, High, Moderate, Low, Nil)",
    resolution: "1:50,000 scale Macro-zonation",
    temporal_coverage: "National Landslide Susceptibility Mapping (NLSM) 2014-2022",
    geographic_coverage: "100% of Meghalaya plateau & Assam hilly districts (Dima Hasao, Karbi Anglong)",
    version: "NLSM 2.0",
    processing_status: "REGISTERED",
    notes: "Official landslide susceptibility zonation for hilly terrain in NE India.",
  },
  {
    dataset_name: "BIS_IS1893_NDMA_Seismic_Zoning",
    factor: "seismic_risk",
    source_name: "Bureau of Indian Standards (BIS) IS 1893:2016 / NDMA",
    provider: "NDMA / BIS",
    official_url: "https://ndma.gov.in/Natural-Hazards/Earthquakes",
    implementation_url: "https://bhuvan-app1.nrsc.gov.in/disaster/disaster.php?id=earthquake",
    source_type: "STANDARDS_VECTOR",
    format: "Vector Polygons (Seismic Zones II to V)",
    resolution: "National / State scale (Macro-seismic zonation)",
    temporal_coverage: "IS 1893 (Part 1): 2016 revision",
    geographic_coverage: "100% of Assam and Meghalaya (All Zone V)",
    version: "IS 1893:2016",
    processing_status: "REGISTERED",
    notes: "Both Assam and Meghalaya lie 100% within Seismic Zone V (Zone factor Z=0.36, severe earthquake hazard).",
  },
  {
    dataset_name: "IndiaWRIS_HydroRIVERS_Drainage_Network",
    factor: "distance_to_river",
    source_name: "Central Water Commission (CWC) India-WRIS / HydroRIVERS v1.0",
    provider: "Ministry of Jal Shakti / WWF HydroSHEDS",
    official_url: "https://indiawris.gov.in/",
    implementation_url: "https://www.hydrosheds.org/products/hydrorivers",
    source_type: "VECTOR_LINESTRING",
    format: "GeoPackage / Shapefile (River centerlines with discharge and stream order)",
    resolution: "15 arc-seconds (~500m detail) & 1:50,000 major rivers",
    temporal_coverage: "Static baseline drainage network",
    geographic_coverage: "Brahmaputra, Barak, Meghna river basins (Assam & Meghalaya)",
    version: "HydroRIVERS v1.0",
    processing_status: "REGISTERED",
    notes: "Used to compute Euclidean / geodesic distance_to_river for all 500m grid cells.",
  },
  {
    dataset_name: "ISRO_SAC_National_Wetlands_Bhuvan_LULC",
    factor: "waterbody_percentage",
    source_name: "Space Applications Centre (SAC/ISRO) & NRSC Bhuvan",
    provider: "NRSC Bhuvan / SAC",
    official_url: "https://vedas.sac.gov.in/en/wetlands.html",
    implementation_url: "https://bhuvan-app1.nrsc.gov.in/2dresources/bhuvanstore.php",
    source_type: "VECTOR_POLYGON",
    format: "Vector Shapefile / GeoJSON (Lakes, Beels, Reservoirs, Rivers, Ponds)",
    resolution: "1:50,000 scale (Wetlands > 2.25 ha)",
    temporal_coverage: "National Wetland Atlas (2020-2022 update)",
    geographic_coverage: "Assam & Meghalaya wetlands and waterbodies",
    version: "2022",
    processing_status: "REGISTERED",
    notes: "Used to calculate waterbody_percentage coverage inside each 500m grid cell.",
  },
  {
    dataset_name: "Census_India_GHSL_Population_Grid",
    factor: "population_density",
    source_name: "Census of India 2011 / Global Human Settlement Layer (GHSL-POP)",
    provider: "Office of the Registrar General of India / European Commission JRC",
    official_url: "https://censusindia.gov.in/",
    implementation_url: "https://human-settlement.emergency.copernicus.eu/ghs_pop2023.php",
    source_type: "RASTER_GEOTIFF",
    format: "GeoTIFF (Persons per grid cell, constrained by Census totals)",
    resolution: "100m - 500m gridded population",
    temporal_coverage: "Census 2011 + 2020/2025 demographic projections",
    geographic_coverage: "100% of Assam and Meghalaya (rural + urban)",
    version: "GHS-POP R2023A",
    processing_status: "REGISTERED",
    notes: "Determines population_density and human exposure for relief priority scoring.",
  },
  {
    dataset_name: "OSM_PMGSY_Transport_Infrastructure",
    factor: "infrastructure_exposure",
    source_name: "OpenStreetMap (Geofabrik North-East) / MoRTH & PMGSY",
    provider: "OpenStreetMap Community / Geofabrik",
    official_url: "https://www.openstreetmap.org/",
    implementation_url: "https://download.geofabrik.de/asia/india/northeast.html",
    source_type: "VECTOR_LINESTRING",
    format: "OSM PBF / GeoJSON (Highways, bridges, primary/secondary/rural roads)",
    resolution: "High-precision vector topology (<5m accuracy)",
    temporal_coverage: "2024-2026 active infrastructure network",
    geographic_coverage: "100% road and bridge network across Assam and Meghalaya",
    version: "2026.08",
    processing_status: "REGISTERED",
    notes: "Provides road density, bridge presence, and critical access corridors for infrastructure_exposure.",
  },
];

async function registerAll() {
  await initRegistrySchema();
  console.log("Registering all 9 static factors into datasets.registry...");

  for (const ds of STATIC_FACTOR_REGISTRY) {
    const res = await upsertDatasetMetadata(ds);
    console.log(`  - [${res.factor.padEnd(25)}] ${res.dataset_name} (${res.processing_status})`);
  }

  const all = await getAllDatasets();
  console.log(`\n✅ Total Registered Datasets: ${all.length}`);
  process.exit(0);
}

registerAll().catch(console.error);
